spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 30
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/elnino
    username: postgres
    password: 1234
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
    driver-class-name: org.postgresql.Driver



serviceName: DefaultDataServiceImpl